name: Delete Akamai Deploy 
inputs:
  environment:
    required: true
    type: string
  directory:
    required: true
    type: string
  filename:
    required: true
    type: string
  cp_code:
    required: true
    type: string
  upload_account:
    required: true
    type: string
  host:
    required: true
    type: string
secrets:
  AKAMAI_NETSTORAGE_CONTENT_API_KEY:
    required: true
runs:
  using: 'node16'
  main: 'delete-script.js'