name: Deploy to Akamai Netstorage
inputs:
  build_artifact_name:
    required: true
    type: string
  environment:
    required: true
    type: string
  scp_endpoint:
    required: true
    type: string
  url:
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - name: Download Build Artifacts
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.build_artifact_name }}

    - name: Copy Build via SCP
      run: |
        mkdir -p ~/.ssh
        echo "$AKAMAI_SSH_KEY" > ~/.ssh/id_rsa
        chmod 400 ~/.ssh/id_rsa
        scp -oStrictHostKeyChecking=no -oHostKeyAlgorithms=+ssh-dss -oPubkeyAcceptedKeyTypes=+ssh-dss ${{ inputs.build_artifact_name }}.zip ${{ inputs.scp_endpoint }}